# Generated by Django 2.2.12 on 2020-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaoxin', '0005_auto_20200716_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
