# Generated by Django 2.2.12 on 2020-07-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaoxin', '0007_auto_20200717_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='finaldepartment',
            field=models.CharField(db_column='finaldepartment', max_length=20, null=True, verbose_name='最终入选部门'),
        ),
        migrations.AddField(
            model_name='student',
            name='nowsta',
            field=models.CharField(db_column='nowst', default='', max_length=20, null=True, verbose_name='现被选部门'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st',
            field=models.CharField(db_column='st', default='', max_length=20, null=True, verbose_name='被录取状态'),
        ),
    ]
