# Generated by Django 2.2.12 on 2020-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaoxin', '0009_auto_20200717_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='command',
            field=models.TextField(db_column='command', default='面试官没写对他的评价，你可以看名字去猜是什么样子的样的人', null=True, verbose_name='面试官评价'),
        ),
    ]
