# Generated by Django 2.2.12 on 2020-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaoxin', '0010_auto_20200717_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
