# Generated by Django 2.2.12 on 2020-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaoxin', '0012_auto_20200717_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentad',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='studentad',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
